# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums/files.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enums/files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nums/files.proto\x12\x05\x65nums*\xec\x01\n\x08SendType\x12\x15\n\x11SEND_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0fSEND_TYPE_PHOTO\x10\x01\x12\x13\n\x0fSEND_TYPE_VIDEO\x10\x02\x12\x13\n\x0fSEND_TYPE_VOICE\x10\x03\x12\x11\n\rSEND_TYPE_GIF\x10\x04\x12\x13\n\x0fSEND_TYPE_AUDIO\x10\x05\x12\x16\n\x12SEND_TYPE_DOCUMENT\x10\x06\x12\x15\n\x11SEND_TYPE_STICKER\x10\x07\x12\x1a\n\x16SEND_TYPE_CROWDFUNDING\x10\x08\x12\x17\n\x13SEND_TYPE_SPONSORED\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums.files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDTYPE']._serialized_start=29
  _globals['_SENDTYPE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
