# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums/groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enums/groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65nums/groups.proto\x12\x05\x65nums*>\n\x0bRestriction\x12\x17\n\x13RESTRICTION_PRIVATE\x10\x00\x12\x16\n\x12RESTRICTION_PUBLIC\x10\x01*U\n\tGroupType\x12\x14\n\x10GROUP_TYPE_GROUP\x10\x00\x12\x16\n\x12GROUP_TYPE_CHANNEL\x10\x01\x12\x1a\n\x16GROUP_TYPE_SUPER_GROUP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums.groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTRICTION']._serialized_start=29
  _globals['_RESTRICTION']._serialized_end=91
  _globals['_GROUPTYPE']._serialized_start=93
  _globals['_GROUPTYPE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
