# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums/peers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enums/peers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nums/peers.proto\x12\x05\x65nums*\xbe\x01\n\nExPeerType\x12\x18\n\x14\x45X_PEER_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x45X_PEER_TYPE_PRIVATE\x10\x01\x12\x16\n\x12\x45X_PEER_TYPE_GROUP\x10\x02\x12\x18\n\x14\x45X_PEER_TYPE_CHANNEL\x10\x03\x12\x14\n\x10\x45X_PEER_TYPE_BOT\x10\x04\x12\x1b\n\x17\x45X_PEER_TYPE_SUPERGROUP\x10\x05\x12\x17\n\x13\x45X_PEER_TYPE_THREAD\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums.peers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPEERTYPE']._serialized_start=29
  _globals['_EXPEERTYPE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
