from .message import Message
from .callback_query import CallbackQuery
from .location import Location
from .audio import Audio
from .thumb import Thumb
from .document import Document
from .video import Video
from .voice import Voice
from .contact import Contact
from .photo import Photo
