# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: structs/set_updates.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'structs/set_updates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..updates import messaging_pb2 as updates_dot_messaging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19structs/set_updates.proto\x12\x07structs\x1a\x17updates/messaging.proto\"J\n\x0f\x43omposedUpdates\x12\x14\n\x0cmessage_sent\x18\x04 \x01(\x0c\x12!\n\x07message\x18\x37 \x01(\x0b\x32\x10.updates.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'structs.set_updates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPOSEDUPDATES']._serialized_start=63
  _globals['_COMPOSEDUPDATES']._serialized_end=137
# @@protoc_insertion_point(module_scope)
