# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: structs/struct.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'structs/struct.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14structs/struct.proto\x12\x07structs*\x9b\x03\n\nTypingType\x12\x17\n\x13TYPING_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10TYPING_TYPE_TEXT\x10\x01\x12\x1f\n\x1bTYPING_TYPE_VOICE_RECORDING\x10\x02\x12\x1d\n\x19TYPING_TYPE_SENDING_VOICE\x10\x03\x12\x1c\n\x18TYPING_TYPE_SENDING_FILE\x10\x04\x12\x1d\n\x19TYPING_TYPE_SENDING_PHOTO\x10\x05\x12\x1d\n\x19TYPING_TYPE_SENDING_VIDEO\x10\x06\x12\x1d\n\x19TYPING_TYPE_SENDING_MUSIC\x10\x07\x12 \n\x1cTYPING_TYPE_CHOOSING_STICKER\x10\x08\x12\x1c\n\x18TYPING_TYPE_CHOOSING_GIF\x10\t\x12$\n TYPING_TYPE_CREATING_GIFT_PACKET\x10\n\x12\x1d\n\x19TYPING_TYPE_SENDING_ALBUM\x10\x0b\x12\x1e\n\x1aTYPING_TYPE_CHOOSING_EMOJI\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'structs.struct_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPINGTYPE']._serialized_start=34
  _globals['_TYPINGTYPE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
