# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests/abacus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'requests/abacus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import peers_pb2 as structs_dot_peers__pb2
from ..structs import messaging_pb2 as structs_dot_messaging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15requests/abacus.proto\x12\x08requests\x1a\x13structs/peers.proto\x1a\x17structs/messaging.proto\"c\n\x0fGetMessageViews\x12\x1b\n\x04peer\x18\x01 \x01(\x0b\x32\r.structs.Peer\x12 \n\x04mids\x18\x02 \x03(\x0b\x32\x12.structs.MessageId\x12\x11\n\tincrement\x18\x03 \x01(\x08\"Z\n\x12MessageSetReaction\x12\x1b\n\x04peer\x18\x01 \x01(\x0b\x32\r.structs.Peer\x12\x0b\n\x03rid\x18\x02 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.abacus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMESSAGEVIEWS']._serialized_start=81
  _globals['_GETMESSAGEVIEWS']._serialized_end=180
  _globals['_MESSAGESETREACTION']._serialized_start=182
  _globals['_MESSAGESETREACTION']._serialized_end=272
# @@protoc_insertion_point(module_scope)
