# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests/files.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'requests/files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import peers_pb2 as structs_dot_peers__pb2
from ..structs import files_pb2 as structs_dot_files__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14requests/files.proto\x12\x08requests\x1a\x13structs/peers.proto\x1a\x13structs/files.proto\"\xca\x01\n\x15GetNasimFileUploadUrl\x12\x15\n\rexpected_size\x18\x01 \x01(\x05\x12\x0b\n\x03\x63rc\x18\x02 \x01(\x03\x12\x0b\n\x03uid\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tmime_type\x18\x05 \x01(\t\x12 \n\x07\x65x_peer\x18\x06 \x01(\x0b\x32\x0f.structs.ExPeer\x12)\n\tsend_type\x18\x07 \x01(\x0b\x32\x16.structs.SendTypeValue\x12\x12\n\nchunk_size\x18\x08 \x01(\x03\"6\n\x0fGetNasimFileUrl\x12#\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x15.structs.FileLocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNASIMFILEUPLOADURL']._serialized_start=77
  _globals['_GETNASIMFILEUPLOADURL']._serialized_end=279
  _globals['_GETNASIMFILEURL']._serialized_start=281
  _globals['_GETNASIMFILEURL']._serialized_end=335
# @@protoc_insertion_point(module_scope)
