# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests/presence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'requests/presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import peers_pb2 as structs_dot_peers__pb2
from .. import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17requests/presence.proto\x12\x08requests\x1a\x13structs/peers.proto\x1a\x0b\x65nums.proto\"0\n\tSetOnline\x12\x11\n\tis_online\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\"P\n\x06Typing\x12\x1e\n\x04peer\x18\x01 \x01(\x0b\x32\x10.structs.OutPeer\x12&\n\x0btyping_type\x18\x03 \x01(\x0e\x32\x11.enums.TypingTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETONLINE']._serialized_start=71
  _globals['_SETONLINE']._serialized_end=119
  _globals['_TYPING']._serialized_start=121
  _globals['_TYPING']._serialized_end=201
# @@protoc_insertion_point(module_scope)
