# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests/request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'requests/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16requests/request.proto\x12\x08requests\".\n\x15MetadataComplexValues\x12\x15\n\rfixed64_value\x18\x06 \x01(\x06\"Z\n\x0eMetadataValues\x12\x14\n\x0cstring_value\x18\x01 \x01(\t\x12\x32\n\tmsg_value\x18\x02 \x01(\x0b\x32\x1f.requests.MetadataComplexValues\"I\n\x11MetadataKeyValues\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.requests.MetadataValues\";\n\x08Metadata\x12/\n\nkey_values\x18\x01 \x03(\x0b\x32\x1b.requests.MetadataKeyValuesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATACOMPLEXVALUES']._serialized_start=36
  _globals['_METADATACOMPLEXVALUES']._serialized_end=82
  _globals['_METADATAVALUES']._serialized_start=84
  _globals['_METADATAVALUES']._serialized_end=174
  _globals['_METADATAKEYVALUES']._serialized_start=176
  _globals['_METADATAKEYVALUES']._serialized_end=249
  _globals['_METADATA']._serialized_start=251
  _globals['_METADATA']._serialized_end=310
# @@protoc_insertion_point(module_scope)
