# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: requests/users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'requests/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import peers_pb2 as structs_dot_peers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14requests/users.proto\x12\x08requests\x1a\x13structs/peers.proto\"\x18\n\x08\x45\x64itName\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\tLoadUsers\x12(\n\nuser_peers\x18\x01 \x03(\x0b\x32\x14.structs.UserOutPeer\"9\n\rLoadFullUsers\x12(\n\nuser_peers\x18\x01 \x03(\x0b\x32\x14.structs.UserOutPeer\"8\n\x0eSearchContacts\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x15\n\roptimizations\x18\x02 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDITNAME']._serialized_start=55
  _globals['_EDITNAME']._serialized_end=79
  _globals['_LOADUSERS']._serialized_start=81
  _globals['_LOADUSERS']._serialized_end=134
  _globals['_LOADFULLUSERS']._serialized_start=136
  _globals['_LOADFULLUSERS']._serialized_end=193
  _globals['_SEARCHCONTACTS']._serialized_start=195
  _globals['_SEARCHCONTACTS']._serialized_end=251
# @@protoc_insertion_point(module_scope)
