# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses/abacus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'responses/abacus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import messaging_pb2 as structs_dot_messaging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16responses/abacus.proto\x12\tresponses\x1a\x17structs/messaging.proto\"=\n\x0fGetMessageViews\x12*\n\ncontainers\x18\x01 \x03(\x0b\x32\x16.structs.MessagesViewsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses.abacus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMESSAGEVIEWS']._serialized_start=62
  _globals['_GETMESSAGEVIEWS']._serialized_end=123
# @@protoc_insertion_point(module_scope)
