# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'responses/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import collections_pb2 as structs_dot_collections__pb2
from ..structs import users_pb2 as structs_dot_users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14responses/auth.proto\x12\tresponses\x1a\x19structs/collections.proto\x1a\x13structs/users.proto\"\x8b\x02\n\x0eStartPhoneAuth\x12\x18\n\x10transaction_hash\x18\x01 \x01(\t\x12\x15\n\ris_registered\x18\x02 \x01(\x08\x12\x16\n\x0esent_code_type\x18\x05 \x01(\x05\x12\x31\n\x14\x63ode_expiration_date\x18\x06 \x01(\x0b\x32\x13.structs.Int64Value\x12\x1b\n\x13next_send_code_type\x18\x07 \x01(\x05\x12\x35\n\x18next_send_code_wait_time\x18\x08 \x01(\x0b\x32\x13.structs.Int64Value\x12)\n\x0c\x63ode_timeout\x18\t \x01(\x0b\x32\x13.structs.Int32Value\"F\n\x04\x41uth\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.structs.User\x12!\n\x03jwt\x18\x04 \x01(\x0b\x32\x14.structs.StringValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTPHONEAUTH']._serialized_start=84
  _globals['_STARTPHONEAUTH']._serialized_end=351
  _globals['_AUTH']._serialized_start=353
  _globals['_AUTH']._serialized_end=423
# @@protoc_insertion_point(module_scope)
