# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses/files.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'responses/files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import files_pb2 as structs_dot_files__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15responses/files.proto\x12\tresponses\x1a\x13structs/files.proto\"@\n\x0fGetNasimFileUrl\x12-\n\x08\x66ile_url\x18\x01 \x01(\x0b\x32\x1b.structs.FileUrlDescription\"p\n\x15GetNasimFileUploadUrl\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tduplicate\x18\x03 \x01(\x08\x12\x12\n\nchunk_size\x18\x04 \x01(\x05\x12\x12\n\nblock_size\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses.files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNASIMFILEURL']._serialized_start=57
  _globals['_GETNASIMFILEURL']._serialized_end=121
  _globals['_GETNASIMFILEUPLOADURL']._serialized_start=123
  _globals['_GETNASIMFILEUPLOADURL']._serialized_end=235
# @@protoc_insertion_point(module_scope)
