# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses/groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'responses/groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import groups_pb2 as structs_dot_groups__pb2
from ..structs import files_pb2 as structs_dot_files__pb2
from ..structs import peers_pb2 as structs_dot_peers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16responses/groups.proto\x12\tresponses\x1a\x14structs/groups.proto\x1a\x13structs/files.proto\x1a\x13structs/peers.proto\"D\n\x0fGetGroupPreview\x12!\n\x05group\x18\x01 \x01(\x0b\x32\x12.structs.FullGroup\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\"5\n\x10LoadGroupAvatars\x12!\n\x07\x61vatars\x18\x01 \x01(\x0b\x32\x10.structs.Avatars\"7\n\tJoinGroup\x12\x1d\n\x05group\x18\x01 \x01(\x0b\x32\x0e.structs.Group\x12\x0b\n\x03seq\x18\x02 \x01(\x05\"=\n\x0fJoinPublicGroup\x12\x1d\n\x05group\x18\x01 \x01(\x0b\x32\x0e.structs.Group\x12\x0b\n\x03seq\x18\x02 \x01(\x05\"6\n\x0cGetFullGroup\x12&\n\nfull_group\x18\x01 \x01(\x0b\x32\x12.structs.FullGroup\"-\n\x14GetGroupMembersCount\x12\x15\n\rmembers_count\x18\x01 \x01(\x05\"A\n\x0bInviteUsers\x12\x32\n\x14not_added_user_peers\x18\x01 \x03(\x0b\x32\x14.structs.UserOutPeer\"=\n\x0bLoadMembers\x12 \n\x07members\x18\x01 \x03(\x0b\x32\x0f.structs.Member\x12\x0c\n\x04next\x18\x02 \x01(\x0c\" \n\x11GetGroupInviteUrl\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x0fRevokeInviteUrl\x12\x0b\n\x03url\x18\x01 \x01(\t\"\\\n\x0f\x45\x64itGroupAvatar\x12\x1f\n\x06\x61vatar\x18\x01 \x01(\x0b\x32\x0f.structs.Avatar\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x0c\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses.groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETGROUPPREVIEW']._serialized_start=101
  _globals['_GETGROUPPREVIEW']._serialized_end=169
  _globals['_LOADGROUPAVATARS']._serialized_start=171
  _globals['_LOADGROUPAVATARS']._serialized_end=224
  _globals['_JOINGROUP']._serialized_start=226
  _globals['_JOINGROUP']._serialized_end=281
  _globals['_JOINPUBLICGROUP']._serialized_start=283
  _globals['_JOINPUBLICGROUP']._serialized_end=344
  _globals['_GETFULLGROUP']._serialized_start=346
  _globals['_GETFULLGROUP']._serialized_end=400
  _globals['_GETGROUPMEMBERSCOUNT']._serialized_start=402
  _globals['_GETGROUPMEMBERSCOUNT']._serialized_end=447
  _globals['_INVITEUSERS']._serialized_start=449
  _globals['_INVITEUSERS']._serialized_end=514
  _globals['_LOADMEMBERS']._serialized_start=516
  _globals['_LOADMEMBERS']._serialized_end=577
  _globals['_GETGROUPINVITEURL']._serialized_start=579
  _globals['_GETGROUPINVITEURL']._serialized_end=611
  _globals['_REVOKEINVITEURL']._serialized_start=613
  _globals['_REVOKEINVITEURL']._serialized_end=643
  _globals['_EDITGROUPAVATAR']._serialized_start=645
  _globals['_EDITGROUPAVATAR']._serialized_end=737
# @@protoc_insertion_point(module_scope)
