# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: responses/messaging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'responses/messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import messaging_pb2 as structs_dot_messaging__pb2
from ..structs import groups_pb2 as structs_dot_groups__pb2
from ..structs import users_pb2 as structs_dot_users__pb2
from ..structs import peers_pb2 as structs_dot_peers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19responses/messaging.proto\x12\tresponses\x1a\x17structs/messaging.proto\x1a\x14structs/groups.proto\x1a\x13structs/users.proto\x1a\x13structs/peers.proto\"9\n\x0bLoadHistory\x12*\n\x07history\x18\x01 \x03(\x0b\x32\x19.structs.MessageContainer\"\xc3\x01\n\x0bLoadDialogs\x12\x1e\n\x06groups\x18\x01 \x03(\x0b\x32\x0e.structs.Group\x12\x1c\n\x05users\x18\x02 \x03(\x0b\x32\r.structs.User\x12 \n\x07\x64ialogs\x18\x03 \x03(\x0b\x32\x0f.structs.Dialog\x12(\n\nuser_peers\x18\x04 \x03(\x0b\x32\x14.structs.UserOutPeer\x12*\n\x0bgroup_peers\x18\x05 \x03(\x0b\x32\x15.structs.GroupOutPeer\"H\n\x12LoadPinnedMessages\x12\x32\n\x0fpinned_messages\x18\x01 \x03(\x0b\x32\x19.structs.MessageContainerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADHISTORY']._serialized_start=129
  _globals['_LOADHISTORY']._serialized_end=186
  _globals['_LOADDIALOGS']._serialized_start=189
  _globals['_LOADDIALOGS']._serialized_end=384
  _globals['_LOADPINNEDMESSAGES']._serialized_start=386
  _globals['_LOADPINNEDMESSAGES']._serialized_end=458
# @@protoc_insertion_point(module_scope)
