# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: updates/messaging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'updates/messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..structs import peers_pb2 as structs_dot_peers__pb2
from ..structs import messaging_pb2 as structs_dot_messaging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17updates/messaging.proto\x12\x07updates\x1a\x13structs/peers.proto\x1a\x17structs/messaging.proto\"\xd9\x01\n\x07Message\x12\x1b\n\x04peer\x18\x01 \x01(\x0b\x32\r.structs.Peer\x12\x12\n\nsender_uid\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x03\x12\x0b\n\x03rid\x18\x04 \x01(\x03\x12!\n\x07message\x18\x05 \x01(\x0b\x32\x10.structs.Message\x12.\n\x0equoted_message\x18\x07 \x01(\x0b\x32\x16.structs.QuotedMessage\x12/\n\x13previous_message_id\x18\t \x01(\x0b\x32\x12.structs.MessageIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'updates.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=83
  _globals['_MESSAGE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
