# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65nums.proto\x12\x05\x65nums*\xec\x01\n\x08SendType\x12\x15\n\x11SEND_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0fSEND_TYPE_PHOTO\x10\x01\x12\x13\n\x0fSEND_TYPE_VIDEO\x10\x02\x12\x13\n\x0fSEND_TYPE_VOICE\x10\x03\x12\x11\n\rSEND_TYPE_GIF\x10\x04\x12\x13\n\x0fSEND_TYPE_AUDIO\x10\x05\x12\x16\n\x12SEND_TYPE_DOCUMENT\x10\x06\x12\x15\n\x11SEND_TYPE_STICKER\x10\x07\x12\x1a\n\x16SEND_TYPE_CROWDFUNDING\x10\x08\x12\x17\n\x13SEND_TYPE_SPONSORED\x10\t*>\n\x0bRestriction\x12\x17\n\x13RESTRICTION_PRIVATE\x10\x00\x12\x16\n\x12RESTRICTION_PUBLIC\x10\x01*U\n\tGroupType\x12\x14\n\x10GROUP_TYPE_GROUP\x10\x00\x12\x16\n\x12GROUP_TYPE_CHANNEL\x10\x01\x12\x1a\n\x16GROUP_TYPE_SUPER_GROUP\x10\x02*\xbe\x01\n\nExPeerType\x12\x18\n\x14\x45X_PEER_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x45X_PEER_TYPE_PRIVATE\x10\x01\x12\x16\n\x12\x45X_PEER_TYPE_GROUP\x10\x02\x12\x18\n\x14\x45X_PEER_TYPE_CHANNEL\x10\x03\x12\x14\n\x10\x45X_PEER_TYPE_BOT\x10\x04\x12\x1b\n\x17\x45X_PEER_TYPE_SUPERGROUP\x10\x05\x12\x17\n\x13\x45X_PEER_TYPE_THREAD\x10\x06*\x9b\x03\n\nTypingType\x12\x17\n\x13TYPING_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10TYPING_TYPE_TEXT\x10\x01\x12\x1f\n\x1bTYPING_TYPE_VOICE_RECORDING\x10\x02\x12\x1d\n\x19TYPING_TYPE_SENDING_VOICE\x10\x03\x12\x1c\n\x18TYPING_TYPE_SENDING_FILE\x10\x04\x12\x1d\n\x19TYPING_TYPE_SENDING_PHOTO\x10\x05\x12\x1d\n\x19TYPING_TYPE_SENDING_VIDEO\x10\x06\x12\x1d\n\x19TYPING_TYPE_SENDING_MUSIC\x10\x07\x12 \n\x1cTYPING_TYPE_CHOOSING_STICKER\x10\x08\x12\x1c\n\x18TYPING_TYPE_CHOOSING_GIF\x10\t\x12$\n TYPING_TYPE_CREATING_GIFT_PACKET\x10\n\x12\x1d\n\x19TYPING_TYPE_SENDING_ALBUM\x10\x0b\x12\x1e\n\x1aTYPING_TYPE_CHOOSING_EMOJI\x10\x0c*4\n\x03Sex\x12\x0f\n\x0bSEX_UNKNOWN\x10\x00\x12\x0c\n\x08SEX_MALE\x10\x01\x12\x0e\n\nSEX_FEMALE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDTYPE']._serialized_start=23
  _globals['_SENDTYPE']._serialized_end=259
  _globals['_RESTRICTION']._serialized_start=261
  _globals['_RESTRICTION']._serialized_end=323
  _globals['_GROUPTYPE']._serialized_start=325
  _globals['_GROUPTYPE']._serialized_end=410
  _globals['_EXPEERTYPE']._serialized_start=413
  _globals['_EXPEERTYPE']._serialized_end=603
  _globals['_TYPINGTYPE']._serialized_start=606
  _globals['_TYPINGTYPE']._serialized_end=1017
  _globals['_SEX']._serialized_start=1019
  _globals['_SEX']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
