# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .structs import collections_pb2 as structs_dot_collections__pb2
from .structs import set_updates_pb2 as structs_dot_set__updates__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ws.proto\x12\x02ws\x1a\x19structs/collections.proto\x1a\x19structs/set_updates.proto\"E\n\nClientPack\x12\x1f\n\nws_request\x18\x01 \x01(\x0b\x32\x0b.ws.Request\x12\x16\n\x04ping\x18\x02 \x01(\x0b\x32\x08.ws.Ping\"\x12\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\x03\"t\n\x07Request\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12#\n\x08metadata\x18\x04 \x01(\x0b\x32\x11.structs.MapValue\x12\r\n\x05index\x18\x05 \x01(\x03\"E\n\x08Response\x12\x18\n\x05\x65rror\x18\x01 \x01(\x0b\x32\t.ws.Error\x12\x10\n\x08response\x18\x02 \x01(\x0c\x12\r\n\x05index\x18\x03 \x01(\x03\"J\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x11.structs.MapValue\"#\n\x06Update\x12\x19\n\x06update\x18\x01 \x01(\x0b\x32\t.ws.Event\"H\n\nServerPack\x12\x1e\n\x08response\x18\x01 \x01(\x0b\x32\x0c.ws.Response\x12\x1a\n\x06update\x18\x02 \x01(\x0b\x32\n.ws.Update\":\n\x05\x45vent\x12\x31\n\x0f\x63omposed_update\x18\x01 \x01(\x0b\x32\x18.structs.ComposedUpdatesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTPACK']._serialized_start=70
  _globals['_CLIENTPACK']._serialized_end=139
  _globals['_PING']._serialized_start=141
  _globals['_PING']._serialized_end=159
  _globals['_REQUEST']._serialized_start=161
  _globals['_REQUEST']._serialized_end=277
  _globals['_RESPONSE']._serialized_start=279
  _globals['_RESPONSE']._serialized_end=348
  _globals['_ERROR']._serialized_start=350
  _globals['_ERROR']._serialized_end=424
  _globals['_UPDATE']._serialized_start=426
  _globals['_UPDATE']._serialized_end=461
  _globals['_SERVERPACK']._serialized_start=463
  _globals['_SERVERPACK']._serialized_end=535
  _globals['_EVENT']._serialized_start=537
  _globals['_EVENT']._serialized_end=595
# @@protoc_insertion_point(module_scope)
